
service: constantly-running
# app and org for use with dashboard.serverless.com
app: database_client
#org: your-org-name



provider:
  name: aws
  runtime: python3.8
  vpc: ${file(./scheduler.yaml):vpc}
  environment: ${file(./scheduler.yaml):database}
  endpointType: REGIONAL
    
custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: ./Dockerfile



functions:

  scheduler_add:
    handler: scheduler_api.add
    events:
    - http:
        path: /scheduler/add
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  scheduler_update:
    handler: scheduler_api.update
    events:
    - http:
        path: /scheduler/update
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15  

  scheduler_fields:
    handler: scheduler_api.request_fields
    events:
    - http:
        path: /scheduler/get_fields
        method: get
    timeout: 5
  
  delayer_fields:
    handler: delayer_api.request_fields
    events:
    - http:
        path: /delayer/get_fields
        method: get
    timeout: 5

  delayer_add:
    handler: delayer_api.add
    events:
    - http:
        path: /delayer/add
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  create-tables:
    handler: api.create_tables
    events:
    - http:
        path: /create_tables
        method: get
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15


plugins:
  - serverless-python-requirements
