
service: constantly-running
# app and org for use with dashboard.serverless.com
app: database_client
#org: your-org-name



provider:
  name: aws
  stage: dev
  runtime: python3.8
  environment: ${file(./scheduler.yaml):database}
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:HeadObject"
        - "s3:PutObject"
      Resource: arn:aws:s3:::basementremodeling-archive-12345/*
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: arn:aws:s3:::email-templates-unique-12345
    - Effect: Allow
      Action:
        - "logs:CreateLogStream"
      Resource: '*'
    - Effect: Allow
      Action:
        - "logs:PutLogEvents"
      Resource: '*'
    
custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: ./Dockerfile

#arn:aws:logs:us-east-1:${file(./scheduler.yaml):account_id}:log-group:scheduler*:*:*

functions:

  add:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: api.add
    events:
    - http:
        path: /add
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  fields:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: api.request_fields
    events:
    - http:
        path: /get_fields
        method: get
    timeout: 5

  delete:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: api.delete_record
    events:
    - http:
        path: /delete
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 5


  update:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: api.update_record
    events:
    - http:
        path: /update
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 5


  fetch-zap-codes:
    handler: api.fetch_zap_codes
    events:
    - http:
        path: /codes
        method: get
    timeout: 5


plugins:
  - serverless-python-requirements
