
service: constantly-running
# app and org for use with dashboard.serverless.com
app: database_client
#org: your-org-name



provider:
  name: aws
  runtime: python3.8
  environment: ${file(./scheduler.yaml):database}
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:HeadObject"
        - "s3:PutObject"
      Resource: arn:aws:s3:::basementremodeling-archive-12345/*
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: arn:aws:s3:::email-templates-unique-12345
        
    
custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: ./Dockerfile



functions:

  scheduler_add:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: scheduler_api.add
    events:
    - http:
        path: /scheduler/add
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  scheduler_update:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: scheduler_api.update
    events:
    - http:
        path: /scheduler/update
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15  

  scheduler_fields:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: scheduler_api.request_fields
    events:
    - http:
        path: /scheduler/get_fields
        method: get
    timeout: 5

  scheduler_delete:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: scheduler_api.delete_record
    events:
    - http:
        path: /scheduler/delete
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 5
  
  delayer_fields:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: delayer_api.request_fields
    events:
    - http:
        path: /delayer/get_fields
        method: get
    timeout: 5

  delayer_add:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: delayer_api.add
    events:
    - http:
        path: /delayer/add
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  delayer_delete:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: delayer_api.delete_record
    events:
    - http:
        path: /delayer/delete
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 5

  delayer_update:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: delayer_api.update
    events:
    - http:
        path: /delayer/update
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 5

  create-tables:
    vpc: ${file(./scheduler.yaml):vpc}
    handler: api.create_tables
    events:
    - http:
        path: /create_tables
        method: get
        authorizer:
          arn: arn:aws:lambda:us-east-1:612185335394:function:utilities-dev-authorizer
    timeout: 15

  fetch-zap-codes:
    handler: api.fetch_zap_codes
    events:
    - http:
        path: /codes
        method: get
    timeout: 5


plugins:
  - serverless-python-requirements
