name: CI

on:
  push:
    branches: [ master ]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Find changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      
    - name: Print changed files
      run: echo ${{steps.files.outputs.all}}

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update config file if needed
      if: contains('steps.files.outputs.all', 'scheduler.conf')
      run: echo Updating config file

    - name: Check AWS access
      run : aws s3 ls
